In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import OrdinalEncoder

In [2]:
import glob
all_files = glob.glob("Storing_csv_files_2" + "/*.csv")
frame = []
for filename in all_files:
    df = pd.read_csv(filename)
    frame.append(df)
original_df = pd.concat(frame)

In [3]:
original_df

,Unnamed: 0,Summary,Issue id,Status,Assignee,Updated,Last Viewed,Original estimate,Time Spent,Custom field (Start date),...,diff_time_spent,percent_random,percent_sign,percentage,Due date,Label,percent_random_time_spent,percent_sign_time_spent,percentage_time_spent,Random_time_spent
0,0,Problem statement,10018,Done,Alexey,3/7/2022 13:12,3/7/2022 13:14,12,19.622701,2021-11-01,...,6,1.225434,2,2.450868,2022-03-02,0,1.135225,2,2.270450,19.622701
1,1,Project Proposal,10019,Done,Angie,NaN,NaN,24,16.182582,2021-11-28,...,4,0.047835,-2,-0.095670,2021-12-31,0,1.522823,2,3.045645,16.182582
2,2,Assign project tasks to the team,10020,Done,Manoj,3/7/2022 13:13,3/7/2022 13:14,2,3.853344,2021-11-30,...,1,1.467797,2,2.935593,2022-04-23,0,1.426672,2,2.853344,3.853344
3,3,Discuss budgeting,10021,Done,Violet,3/7/2022 13:04,3/7/2022 13:14,4,0.000000,2021-12-01,...,0,1.870390,2,3.740780,2022-05-17,0,0.991062,2,1.982123,0.000000
4,4,Software Requirements Document,10022,Done,Latifah,3/7/2022 13:04,3/7/2022 13:14,48,89.600950,2021-12-02,...,24,1.473269,2,2.946539,2022-04-25,0,1.366686,2,2.733373,89.600950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,15,View Foreign Exchange account,10033,Done,Latifah,3/7/2022 13:07,3/7/2022 13:14,36,-44.080124,2022-03-13,...,-12,1.637118,2,3.274236,2022-06-16,0,1.336672,2,2.673344,-44.080124
16,16,Exchange currency tab,10034,Done,Latifah,3/7/2022 12:58,3/7/2022 13:14,48,23.871948,2022-04-04,...,10,0.005432,-2,-0.010863,2022-04-20,0,0.693597,2,1.387195,23.871948
17,17,User testing,10035,Done,Sunny,3/7/2022 12:56,3/7/2022 13:14,8,-4.324125,2022-04-15,...,-1,1.494751,2,2.989502,2022-06-29,0,1.662063,2,3.324125,-4.324125
18,18,Vendors testing the software for any bugs,10036,Done,Terry/Rosemary/Lyte,3/7/2022 12:56,3/7/2022 13:14,24,15.027167,2022-04-26,...,10,0.633597,2,1.267194,2022-06-24,0,0.251358,2,0.502717,15.027167
19,19,Releasing 2.0,10037,Done,Angie,3/7/2022 13:06,3/7/2022 13:14,9,12.184136,2022-05-24,...,5,0.333757,2,0.667515,2022-07-22,0,0.718414,2,1.436827,12.184136

In [4]:
original_df['Status'].fillna('Done', inplace = True)
transform_df = original_df[['Status','Assignee']]
print(transform_df)

encoder = OrdinalEncoder()
encoder.fit(transform_df)
final_df = encoder.transform(transform_df)
print(final_df)
#final_df = pd.DataFrame(final_df, columns = ['Status', 'Label(Binary) Project with all tasks', 'Assignee' ])
#final_df = pd.concat([final_df, original_df], axis = 1, ignore_indexing = True)
#final_df

   Status             Assignee
0    Done               Alexey
1    Done                Angie
2    Done                Manoj
3    Done               Violet
4    Done              Latifah
..    ...                  ...
15   Done              Latifah
16   Done              Latifah
17   Done                Sunny
18   Done  Terry/Rosemary/Lyte
19   Done                Angie

[20000 rows x 2 columns]
[[ 0.  1.]
 [ 0.  2.]
 [ 0.  8.]
 ...
 [ 0. 11.]
 [ 0. 12.]
 [ 0.  2.]]

In [5]:
arr = original_df[['diff_dates','percent_random', 'Original estimate', 'diff_time_spent', 'Time Spent']].to_numpy()

In [13]:
X = original_df[['diff_dates','percent_random', 'Original estimate', 'diff_time_spent', 'Time Spent', 'Label']]
y = original_df['Label']

In [14]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

X['Label'] = le.fit_transform(X['Label'])

y = le.transform(y)

C:\Users\Meep\AppData\Local\Temp/ipykernel_6912/1957488410.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Label'] = le.fit_transform(X['Label'])

In [7]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20000 entries, 0 to 19
Data columns (total 23 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Unnamed: 0                            20000 non-null  int64
 1   Summary                               20000 non-null  object
 2   Issue id                              20000 non-null  int64
 3   Status                                20000 non-null  object
 4   Assignee                              20000 non-null  object
 5   Updated                               19000 non-null  object
 6   Last Viewed                           19000 non-null  object
 7   Original estimate                     20000 non-null  int64
 8   Time Spent                            20000 non-null  float64
 9   Custom field (Start date)             20000 non-null  object
 10  Dependency                            19000 non-null  float64
 11  Label(Binary) Project with all tasks  20000 non-null  object
 12  diff_dates                            20000 non-null  float64
 13  diff_time_spent                       20000 non-null  int64
 14  percent_random                        20000 non-null  float64
 15  percent_sign                          20000 non-null  int64
 16  percentage                            20000 non-null  float64
 17  Due date                              20000 non-null  object
 18  Label                                 20000 non-null  int64
 19  percent_random_time_spent             20000 non-null  float64
 20  percent_sign_time_spent               20000 non-null  int64
 21  percentage_time_spent                 20000 non-null  float64
 22  Random_time_spent                     20000 non-null  float64
dtypes: float64(8), int64(7), object(8)
memory usage: 3.7+ MB

In [8]:
X.head()

,Unnamed: 0,Summary,Issue id,Status,Assignee,Updated,Last Viewed,Original estimate,Time Spent,Custom field (Start date),...,diff_time_spent,percent_random,percent_sign,percentage,Due date,Label,percent_random_time_spent,percent_sign_time_spent,percentage_time_spent,Random_time_spent
0,0,Problem statement,10018,Done,Alexey,3/7/2022 13:12,3/7/2022 13:14,12,19.622701,2021-11-01,...,6,1.225434,2,2.450868,2022-03-02,0,1.135225,2,2.270450,19.622701
1,1,Project Proposal,10019,Done,Angie,NaN,NaN,24,16.182582,2021-11-28,...,4,0.047835,-2,-0.095670,2021-12-31,0,1.522823,2,3.045645,16.182582
2,2,Assign project tasks to the team,10020,Done,Manoj,3/7/2022 13:13,3/7/2022 13:14,2,3.853344,2021-11-30,...,1,1.467797,2,2.935593,2022-04-23,0,1.426672,2,2.853344,3.853344
3,3,Discuss budgeting,10021,Done,Violet,3/7/2022 13:04,3/7/2022 13:14,4,0.000000,2021-12-01,...,0,1.870390,2,3.740780,2022-05-17,0,0.991062,2,1.982123,0.000000
4,4,Software Requirements Document,10022,Done,Latifah,3/7/2022 13:04,3/7/2022 13:14,48,89.600950,2021-12-02,...,24,1.473269,2,2.946539,2022-04-25,0,1.366686,2,2.733373,89.600950

In [47]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=2, random_state=100) 

kmeans.fit(X)

KMeans(n_clusters=2, random_state=100)

In [48]:
kmeans.cluster_centers_

array([[1.92096063e+01, 9.96420285e-01, 2.01382854e+01, 4.79033789e+00,
        1.21294420e+01, 1.12203295e-01],
       [1.76859189e+01, 1.00767017e+00, 7.84840095e+01, 4.73646778e+01,
        1.58562271e+02, 9.54653938e-03]])

In [49]:
labels = kmeans.labels_

# check how many of the samples were correctly labeled
correct_labels = sum(y == labels)

print("Result: %d out of %d samples were correctly labeled." % (correct_labels, y.size))

Result: 15916 out of 20000 samples were correctly labeled.

In [50]:
print('Accuracy score: {0:0.2f}'. format(correct_labels/float(y.size)))

Accuracy score: 0.80